### ISSUE TITLE
Comaptibility with Julia 1.1

### ISSUE THREAD

**Issue by ayadlin** [lopezm94/SugarBLAS.jl#8]
Hi,

I am new to Julia!

Is this (or will it be) compatible with Julia 1.1?

Getting this error
Am I doing something wrong or is the package simply not yet compatible with julia 1.1?

(v1.1) pkg> add SugarBLAS
  Updating registry at `C:\Users\alewolf\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package SugarBLAS [0999239e]:
 SugarBLAS [0999239e] log:
 ├─possible versions are: 0.0.1-0.0.4 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.0.1-0.0.4
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

Thanks and take care!

Ale

**Comment by lopezm94** [comment]
Hey @ayadlin, sorry for the delay. You should be able to use the package once the new version is [merged]((https://github.com/JuliaLang/METADATA.jl/pull/22562)) into `METADATA.jl`.

If don't want to wait you can just use the package by executing the following:

```julia
using Pkg
Pkg.clone("https://github.com/lopezm94/SugarBLAS.jl.git", "SugarBLAS")
```

Im going to close this issue since you shouldn't have any more problems, otherwise reopen it.

**Comment by lopezm94** [comment]
You can track if the new version has been merged [here](https://github.com/JuliaLang/METADATA.jl/pull/22562)

**Comment by ayadlin** [comment]
Thanks :)
